language: node_js
node_js: '12'

os:
  - linux

script:
  - npm run check:themes
  - npm run lint
  - npm run test:unit -- --coverage
  # if SauceLabs variables are defined, build docs and run visual regression tests
  - 'if [ -z "$SAUCE_ACCESS_KEY" ]; then true; else npm run docs; fi'
  - 'if [ -z "$SAUCE_ACCESS_KEY" ]; then true; else npm run test:visual; fi'

after_success:
  # Upload code coverage to Codecov
  - bash <(curl -s https://codecov.io/bash)
  # Upload screenshots to Argos
  - 'if [ -z "$ARGOS_TOKEN" ]; then true; else argos upload test/screenshots/local -C "$TRAVIS_COMMIT" -B "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" -T "$ARGOS_TOKEN"; fi'

before_deploy:
  - npm run build
  - ASSET_PATH=/thema/ npm run docs

deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      all_branches: true

  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: ./docs
    on:
      branch: master
